#!/usr/bin/env bash
set -euo pipefail
readonly bin=$1

readonly scriptDir=$(dirname $0)

readonly tmpDir=/tmp/jaremap-test-$$
trap "rm -rf $tmpDir" EXIT
mkdir -p $tmpDir

function main
{
  run_test simple_class_rename
  run_test colliding_class_rename
  #run_test simple_method_rename
  echo OK
}

function run_test
{
  echo "$*"
  "$@"
}

function simple_class_rename
{
  echo "class Hello Goodbye" > $tmpDir/remap.txt
  $bin/jaremap -i $scriptDir/Hello.class -r $tmpDir/remap.txt -p > $tmpDir/remapped.out
  diff -Naurw $scriptDir/simple_rename.expected $tmpDir/remapped.out
}

function simple_method_rename
{
  echo "method HelloFunctions doSomething doBetter" > $tmpDir/remap.txt
  $bin/jaremap -i $scriptDir/HelloFunctions.class -r $tmpDir/remap.txt -p > $tmpDir/remapped.out
  diff -Naurw $scriptDir/simple_method_rename.expected $tmpDir/remapped.out
}

function colliding_class_rename
{
  echo "class CollidingName This_Is_A_Class" > $tmpDir/remap.txt
  $bin/jaremap -i $scriptDir/HelloWithCollision.class -r $tmpDir/remap.txt -p > $tmpDir/remapped.out
  diff -Naurw $scriptDir/colliding_class_rename.expected $tmpDir/remapped.out
}

main
